version: '3'
services:
  web:
    build: .
    command: bash -c " rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' "
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
      - chrome
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports: 
      - "4306:3306"
    volumes:
      # host:container
      - ./tmp/db/mysql:/var/lib/mysql
  smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
  chrome:
    image: selenium/standalone-chrome:3.141.59-dubnium
    ports:
      - 4444:4444
    tty: true
    stdin_open: true
    environment:
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
volumes:
  db-volume: